### PR TITLE
Pass new translateX value through SwipeRow onRowOpen.

### PR DESCRIPTION
**Pull request by CJStroud**
I've added the toValue as a param for onRowOpen function you can pass as a prop to SwipeRow when using it on it's own, which was my initial use case and this works perfectly :)

I'm not sure about how to go about adding it to the SwipeListView though? The toValue is calculated within the SwipeRow component and can't be accessed by the SwipeListView.

### CODE REVIEW

**Comment by jemise111** [comment]
@CJStroud awesome! Can you do me a favor and just add this to the Readme so other people know to use it as well. Also if you want to give it a shot to pass it through to the SwipeListView you could change these lines:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L78

and

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeListView.js#L89

from

`onRowOpen={ _ => this.onRowOpen(secId, rowId, this._rows) }`

to something like

`onRowOpen={ translateX => this.onRowOpen(secId, rowId, this._rows, translateX) }

and test it out. I think that might do the trick.

But at the very least just add some notes to the Readme and I'll be happy to merge this in, thanks!

**Comment by jemise111** [comment]
@CJStroud Going to merge this in so I can close your open issue but have a look at my previous comment, it would be awesome if you could try to make those changes, thanks!

**Comment by jemise111** [comment]
fixes #73

**Comment by jdmunro** [comment]
@jemise111 This is mentioned as being in the 0.3.2 release, however checking the source out this doesn't seem to have been merged: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L189

Any chance we can get this merged and released?

**Comment by jemise111** [comment]
@jdmunro Wow I mean to close the issue but I closed the PR by accident! Good find, thanks for the heads up. I'll release 0.3.3 in a few min and it'll be there, thanks!

**Comment by jdmunro** [comment]
No worries! Thanks, I'll take a look 👍

**Comment by jdmunro** [comment]
Thanks this is all sorted now :)

**Pull request merged**
