### PR TITLE
Add SectionList supported

### PR DESCRIPTION
**Pull request by wuhenzhizao**
@jemise111 , I modified several lines code to support swipe function on SectionList, added a optional property called "useSectionList", but it's better to add a property named "type" as below:
```javascript
type: PropTypes.oneOfType(['readerListView', 'ListView', 'FlatList', 'SectionList'])
```

### CODE REVIEW

**Comment by wuhenzhizao** [comment]
It works well on my device

**Comment by jemise111** [comment]
Hey @wuhenzhizao thanks for the new PR. I'm having trouble running the example though. All I'm seeing is this when I tap on the "SectionList" tab.

image

**Comment by wuhenzhizao** [comment]
SwipeListView and SwipeRow in example are imported from npm, you can use the local ones.

**Comment by wuhenzhizao** [comment]
I have kept the minimum amount of change

**Comment by jemise111** [comment]
@wuhenzhizao Ah my bad, that was dumb. Ran into a different error though. I commented on the code change. Thanks!

**Comment by jemise111** [comment]
@wuhenzhizao I appreciate all of the work you did on this. The formatting and other issues were address on a different PR so I'm going to go ahead and close this one

**Pull request closed without merging**
