### PR TITLE
refactor + overscroll, fastswipe, maxdistance, elastic, event binding

### PR DESCRIPTION
**Pull request by braco**
In addition to the details in 

https://github.com/jemise111/react-native-swipe-list-view/pull/41

Added new props / features on top of those:
- onOverscrollRight
- onOverscrollLeft

And enhanced some other features
- Removed some of the inline functions. [see why](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)
- Use class + arrow properties to maintain self reference
- Pass rowId and sectionId into SwipeRow so it has a reference to itself
- Wrap onEvent functions so they all return the section and rowId

Should probably create equivalent functionality in the React.cloneElement custom element, seems pretty crippled right now

This PR is only what I'm delivering, I just thought other users might find this handy. Not tested very thoroughly. I'll probably fork a new project at some point if this starts deviating too far from the core. Let me know how to reproduce any bugs and I'll take a look.

@jemise111 : you might want to consider an .eslint for this project, it would help with contributions and code quality (it helps me!). Use airbnb's eslint if you don't know where to start.

### CODE REVIEW

**Comment by braco** [comment]
This is how I'm using most of these new features:

```
      <SwipeListView
        closeOnRowPress={true}
        dataSource={dataSource.cloneWithRows(this.props.items)}
        elasticOverscroll={true}
        enableEmptySections={true}
        leftOpenValue={leftSize}
        maxLeftSwipeDistance={leftSize}
        maxRightSwipeDistance={-rightSize}
        onFastSwipeLeft={this.likeRow}
        onFastSwipeRight={this.dislikeRow}
        onOverscrollLeft={this.likeRow}
        onOverscrollRight={this.dislikeRow}
        renderHiddenRow={this.renderRowButtons}
        renderRow={this.renderRowContent}
        rightOpenValue={-rightSize}
      />
```

likeRow and dislikeRow both get rowId, so it's easy to fire an action from that.

**Comment by basequatro** [comment]
This looks great so far. Congrats @braco 
@jemise111 anyway to get this on the new release?

**Comment by jemise111** [comment]
@braco This looks great, thanks for all the work on this! I should have some time tomorrow to go through it and test it out, then should be able to merge and release a new version.

I see there are conflicts though. Would you find fixing those when you get a chance.

**Comment by basequatro** [comment]
maxdistance is very useful, @jemise111 can you please merge this?

**Comment by jemise111** [comment]
@braco Sorry for the delay, just been very busy lately. There are conflicts so this can't be merged in its current state. Can you take care of those please?

Also can you shoot me an email when you have a sec: jesse.sessler (at) gmail (dot) com. Since this is a big rewrite of the library I want to talk to about being a maintainer. Thanks!

**Comment by Druux** [comment]
Are there any updates on the merge conflicts? The over swipe feature would be highly needed. I could contribute on that if nothing happens with this PR.

**Comment by ItsNoHax** [comment]
@braco Was going through your pull request and your:
`        maxLeftSwipeDistance={leftSize}
        maxRightSwipeDistance={rightSize}`

is duplicating 

` stopLeftSwipe={leftSize}  
  stopRightSwipe={rightSize} `

**Comment by xavierlefevre** [comment]
I wanted to use this PR for our project, because we need to implement a "scroll far to delete on drag end"
However it seems that we can't know if we went back from the overscroll, from what I understood, in order to cancel the delete

**Comment by braco** [comment]
@ItsNoHax: thank you, I'll take a look if I get back to this

@xavierlefevre: sounds reasonable, maybe submit a PR with onDragEnd that passes the current coordinates back to the function:

`onDragEnd={(position) => if position.x > nn, do thing}`

**Comment by jemise111** [comment]
Closing as this has been inactive for a while...

**Pull request closed without merging**
