### PR TITLE
First row slideout preview

### PR DESCRIPTION
**Pull request by jemise111**

### CODE REVIEW

**Comment by jemise111** [comment]
Fixes #50

**Comment by basdvries** [comment]
nice work!! could you make this version available via npm? I want to push an update of my app in a couple of hours and it would be awesome if we could push this as well :)

**Comment by jemise111** [comment]
@basdvries done! Let me know if you have any issues

v0.3.0 :)

**Comment by basequatro** [comment]
Its possible to have preview for both sides?

**Pull request merged**
