### PR TITLE
allow pass styles to SwipeRow

### PR DESCRIPTION
**Pull request by jemise111**

### CODE REVIEW

**Comment by chandlervdw** [comment]
Will this be merged soon? Yo quiero. Yo necesito.

**Comment by jemise111** [comment]
Hey @chandlervdw sorry for the delay. I just merged. I have a few issues / PRs to take care of so I'll do a release with this and all the new stuff over the weekend. Until then you can point to master if you like. Thanks!

**Comment by jemise111** [comment]
fixes #39

**Comment by chandlervdw** [comment]
@jemise111 thanks! Quick question — does this only cover the scenario where you might utilize `renderRow` and `renderHiddenRow` inside of `<SwipeListView>` and not the scenario where you might only have `renderRow` with a `<SwipeRow>` inside?

**Comment by jemise111** [comment]
@chandlervdw exactly.

Use the ```swipeRowStyle``` prop if you're using ```renderRow``` and ```renderHiddenRow```

Use the ```style``` prop if you're passing a ```SwipeRow``` to ```renderRow```

**Pull request merged**
