### PR TITLE
Fix PropTypes deprecation warning

### PR DESCRIPTION
**Pull request by thomasMary**
link to #130

### CODE REVIEW

**Comment by wvteijlingen** [comment]
@jemise111 Can we get this merged in and released? The library is unusable with the latest version of React now.

**Comment by elieteyssedou** [comment]
Please, merge the PR. :)

**Comment by boomfly** [comment]
+1

**Comment by latusaki** [comment]
Don't you need to add prop-types in package.json ?

**Comment by hprobotic** [comment]
No one maintains this repo???

**Comment by latusaki** [comment]
I have fixed this to work with RN 16, but did not come around to making a PR yet. Maybe you can do it ? https://github.com/latusaki/react-native-swipe-list-view/tree/prop_type_fix

**Comment by latusaki** [comment]
woops, this is a PR, ignore me 🤣

**Comment by jemise111** [comment]
@thomasMary Thanks for taking care of this!

@Everyone else - apologies for the delay. Will be much more responsive going forward. Thanks for understanding!

**Comment by jemise111** [comment]
Fixed in v0.4.2

**Comment by elieteyssedou** [comment]
Thank you @jemise111 ! Do you need help to maintain the project ?

**Comment by jemise111** [comment]
@elieteyssedou I appreciate the offer. I have a little more time on my hands so I'm okay for now. But I may take you up on it in the futuref

**Pull request merged**
